In [1]:
import numpy as np

In [3]:
A = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
])

B = np.array([
    [1,2],
    [3,4],
    [5,6],
    [7,8]
])

AB = np.matmul(A, B)
AB

array([[ 50,  60],
       [114, 140],
       [178, 220]])

In [9]:
Af = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
Bf = np.array([1,2,3,4,5,6,7,8])

Arows = 3
Acols = 4

Brows = 4
Bcols = 2

# the same is ID = Brows
ID = Acols

Cf = np.zeros(6)

for row in range(Arows):
    for col in range(Bcols):
        for k in range(ID):
            Cf[row*Bcols + col] += Af[row*Acols + k] * Bf[k*Bcols + col]

In [10]:
Cf

array([ 50.,  60., 114., 140., 178., 220.])

In [11]:
Cf.reshape([3, 2])

array([[ 50.,  60.],
       [114., 140.],
       [178., 220.]])

Compare `C` and reshaped `Cf`. They are the same despite the fact `Cf` was calculated on a "linear" address space.